[workspace]
members = [
    "evm"
]


[workspace.dependencies]
k256 = {version = "^0.12"}
sha3 = {version = "^0.10"}

anyhow = "1.0.68"

serde_json = "^1.0"
serde = {version = "1.0.147", features = ["derive"] }